name: Build Development

on:
  push:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    
    - name: Install Amazon.Lambda.Tools
      run: dotnet tool install -g Amazon.Lambda.Tools

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Build
      run: cd OWCE_Web && dotnet lambda deploy-function --configuration Release --function-name OWCE_WebDev --msbuild-parameters "/p:PublishReadyToRun=true --self-contained false --runtime linux-x64"

