name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    - name: Install Amazon.Lambda.Tools
      run: dotnet tool install -g Amazon.Lambda.Tools

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    -name: Move to correct directory
      run: cd OWCE_Web
      run: pwd
      run: ls -la

    #- name: Install dependencies
    #  run: dotnet restore
    - name: Build
      run: dotnet lambda deploy-function --function-name OWCE_Web --msbuild-parameters "/p:PublishReadyToRun=true --self-contained false --runtime linux-x64"

      #run: dotnet build --configuration Release --no-restore
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal
